/**
 * generated by Xtext 2.19.0
 */
package org.xtext.botGenerator;

import org.xtext.botGenerator.AbstractBotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BotRuntimeModule extends AbstractBotRuntimeModule {
}
