/**
 * generated by Xtext 2.19.0
 */
package org.xtext.botGenerator;

import org.xtext.botGenerator.BotStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BotStandaloneSetup extends BotStandaloneSetupGenerated {
  public static void doSetup() {
    new BotStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
