/*
 * generated by Xtext 2.20.0
 */
package org.xtext.botGenerator.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.botGenerator.ui.internal.BotGeneratorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BotGeneratorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BotGeneratorActivator activator = BotGeneratorActivator.getInstance();
		return activator != null ? activator.getInjector(BotGeneratorActivator.ORG_XTEXT_BOTGENERATOR_BOT) : null;
	}

}
