/**
 * generated by Xtext 2.19.0
 */
package org.xtext.botGenerator.ide;

import org.xtext.botGenerator.ide.AbstractBotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BotIdeModule extends AbstractBotIdeModule {
}
