/*
 * generated by Xtext 2.20.0
 */
package org.xtext.botGenerator.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBotScopeProvider extends DelegatingScopeProvider {
}
