<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bla2" nsURI="bla2" nsPrefix="bla2">
  <eClassifiers xsi:type="ecore:EClass" name="BrownPerson" eSuperTypes="//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="//Animal //Rational">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="azucar" eType="//Azucar" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedPerson" eSuperTypes="//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoldePerson" eSuperTypes="//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Azucar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Animal" eSuperTypes="//Food">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eat" eType="//Food"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drink" eType="//Water"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rational"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dog" eSuperTypes="//Animal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drink" eType="//Water"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leg" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Water"/>
  <eClassifiers xsi:type="ecore:EClass" name="Food"/>
</ecore:EPackage>
