/*
 * generated by Xtext 2.19.0
 */
package org.xtext.botGenerator


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BotStandaloneSetup extends BotStandaloneSetupGenerated {

	def static void doSetup() {
		new BotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
