<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pablo" nsURI="pablo" nsPrefix="pablo">
  <eClassifiers xsi:type="ecore:EClass" name="Study" eSuperTypes="//Degree"/>
  <eClassifiers xsi:type="ecore:EClass" name="Degree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="job" eType="//Job" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job">
    <eStructuralFeatures xsi:type="ecore:EReference" name="be" eType="//Degree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cv">
    <eStructuralFeatures xsi:type="ecore:EReference" name="job" eType="//Job" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mark" eSuperTypes="//Degree"/>
</ecore:EPackage>
