/*
 * generated by Xtext 2.23.0
 */
package botGenerator.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link BotWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractBotWebModule extends DefaultWebModule {

}
