/*
 * generated by Xtext 2.23.0
 */
package botGenerator.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.botGenerator.BotRuntimeModule;
import org.xtext.botGenerator.BotStandaloneSetup;
import org.xtext.botGenerator.ide.BotIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class BotWebSetup extends BotStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BotRuntimeModule(), new BotIdeModule(), new BotWebModule()));
	}
	
}
