<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="garage" nsURI="garage" nsPrefix="garage">
  <eClassifiers xsi:type="ecore:EClass" name="Garage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" lowerBound="1" upperBound="-1" eType="//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handler" lowerBound="1" eType="//TicketHandler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clients" lowerBound="1" upperBound="-1" eType="//Client" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ticket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" lowerBound="1" eType="//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiere" lowerBound="1" upperBound="-1" eType="//RepairAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fix" lowerBound="1" eType="//Vehicle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepairAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Motorbike" eSuperTypes="//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brand" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registration" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fixedBy" lowerBound="1" upperBound="-1" eType="//Ticket"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Truck" eSuperTypes="//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Car" eSuperTypes="//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" lowerBound="1" upperBound="-1" eType="//Vehicle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TicketHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="closedTickets" upperBound="-1" eType="//Ticket" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="openTickets" upperBound="-1" eType="//Ticket" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
