<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="casa" nsURI="casa" nsPrefix="casa">
  <eClassifiers xsi:type="ecore:EClass" name="CampaignPlanner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="marketingCampaigns" lowerBound="1" upperBound="-1" eType="//MarketingCampaign" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" lowerBound="1" upperBound="-1" eType="//Employee" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarketingCampaign"/>
  <eClassifiers xsi:type="ecore:EClass" name="Employee"/>
</ecore:EPackage>
