<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="recommenderQuestionnaire" nsURI="recommenderQuestionnaire" nsPrefix="recommenderQuestionnaire">
  <eClassifiers xsi:type="ecore:EClass" name="Questionnaire">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tools" lowerBound="1" upperBound="-1"
        eType="#//Tool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="questions" lowerBound="1"
        upperBound="-1" eType="#//Question" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" eSuperTypes="#//WithName">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aceptedOptions" lowerBound="1"
        upperBound="-1" eType="#//Answer" eOpposite="#//Answer/aceptedTools"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unknown" upperBound="-1"
        eType="#//Answer" eOpposite="#//Answer/unknown"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refusedOptions" upperBound="-1"
        eType="#//Answer" eOpposite="#//Answer/refusedTools"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question" eSuperTypes="#//WithName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiresponse" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answers" lowerBound="1"
        upperBound="-1" eType="#//Answer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluation" eSuperTypes="#//Question"/>
  <eClassifiers xsi:type="ecore:EClass" name="Answer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aceptedTools" lowerBound="1"
        upperBound="-1" eType="#//Tool" eOpposite="#//Tool/aceptedOptions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refusedTools" upperBound="-1"
        eType="#//Tool" eOpposite="#//Tool/refusedOptions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unknown" upperBound="-1"
        eType="#//Tool" eOpposite="#//Tool/unknown"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WithName" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
