/**
 * generated by Xtext 2.19.0
 */
package org.xtext.botGenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.botGenerator.ui.AbstractBotUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BotUiModule extends AbstractBotUiModule {
  public BotUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
