<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testfer" nsURI="testfer" nsPrefix="testfer">
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="//Tablet //Pc //Web //Phone">
    <eStructuralFeatures xsi:type="ecore:EReference" name="run" eType="//Program"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tablet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="os" eType="//Os" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="os" eType="//Os" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Web">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectTo" eType="//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phone">
    <eStructuralFeatures xsi:type="ecore:EReference" name="os" eType="//Os" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoke" eType="//Program"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bot" eSuperTypes="//Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Telegrambot" eSuperTypes="//Bot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="//Pc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="run" eType="//Program"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Os">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kernel"/>
  </eClassifiers>
</ecore:EPackage>
