/**
 * generated by Xtext 2.19.0
 */
package org.xtext.botGenerator.ui.contentassist;

import org.xtext.botGenerator.ui.contentassist.AbstractBotProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BotProposalProvider extends AbstractBotProposalProvider {
}
