<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transportCompany" nsURI="transportCompany" nsPrefix="transportCompany">
  <eClassifiers xsi:type="ecore:EClass" name="GoodsTransportCompany">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handle" upperBound="-1" eType="//Delivery"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delivery">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" upperBound="-1" eType="//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="Heavy" eSuperTypes="//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fragile" eSuperTypes="//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bulky" eSuperTypes="//Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height"/>
  </eClassifiers>
</ecore:EPackage>
